name: Test Action

on:
  push:
    branches:
      - api  # or any branch you want to trigger the action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 22f3002114@ds.study.iitm.ac.in
        run: echo "Hello, world!"
